#!/bin/zsh
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
node --check "$ROOT/src/main.js"
python3 -m py_compile "$ROOT/src/coordinator.py" "$ROOT/src/state-store.py" "$ROOT/src/web-preflight.py" "$ROOT/src/capacity-preflight.py" "$ROOT/src/local-query.py" "$ROOT/src/ask-wrapper.py" "$ROOT/src/ego-runner.py"
zsh -n "$ROOT/bin/chat-bridge"
zsh -n "$ROOT/scripts/install.sh"
zsh -n "$ROOT/scripts/uninstall.sh"
zsh -n "$ROOT/scripts/install-watchdog.sh"
zsh -n "$ROOT/scripts/uninstall-watchdog.sh"
zsh -n "$ROOT/scripts/install-coordinator.sh"
zsh -n "$ROOT/scripts/uninstall-coordinator.sh"
grep -q 'modelPreset' "$ROOT/src/model-policy.js"
grep -q 'project-conductor' "$ROOT/skills/project-conductor/SKILL.md"
grep -q 'task.newPage()' "$ROOT/src/main.js"
grep -q 'delete is destructive; pass --confirm' "$ROOT/src/main.js"
grep -q 'delete-conversation-confirm-button' "$ROOT/src/main.js"
grep -q 'space prune' "$ROOT/src/main.js"
grep -q 'runtime.json' "$ROOT/src/main.js"
grep -q 'spaceName' "$ROOT/src/main.js"
grep -q 'Unknown active chat' "$ROOT/src/main.js"
grep -q '"type": "module"' "$ROOT/package.json"
if grep -q 'chat-bridge-new-' "$ROOT/src/main.js"; then
  echo "per-session Space creation path must not return" >&2
  exit 1
fi

grep -q 'RUNNING_ACTIVE' "$ROOT/src/main.js"
grep -q 'SUSPECT_STALL' "$ROOT/src/main.js"
grep -q 'data-message-id' "$ROOT/src/main.js"
grep -q 'MutationObserver' "$ROOT/src/main.js"
grep -q 'gradedRecover' "$ROOT/src/main.js"
grep -q 'cmd==="watch"' "$ROOT/src/main.js"
grep -q 'AWAITING_DURABLE_UPDATE' "$ROOT/src/main.js"
grep -q 'normalizeCompletionMode' "$ROOT/src/main.js"
grep -q 'completionMode' "$ROOT/src/main.js"
grep -q 'StartInterval' "$ROOT/scripts/install-watchdog.sh"
grep -q '"version": "0.9.0"' "$ROOT/package.json"

grep -q 'local-query.py' "$ROOT/scripts/install.sh"
grep -q 'ego-runner.py' "$ROOT/scripts/install.sh"
grep -q 'EGO_CLIENT_TIMEOUT' "$ROOT/src/ego-runner.py"
grep -q 'ask-wrapper.py' "$ROOT/scripts/install.sh"
grep -q 'cmd==="project"' "$ROOT/src/main.js"
grep -q 'ensureProjectLocation' "$ROOT/src/main.js"
grep -q 'space.*consolidate' "$ROOT/src/main.js"
grep -q 'CONTEXT_EXHAUSTED' "$ROOT/src/main.js"
grep -q 'detachTerminalTaskPages' "$ROOT/src/main.js"
grep -q 'def result_ack' "$ROOT/src/coordinator.py"
grep -q 'def broadcast_management' "$ROOT/src/coordinator.py"
grep -q 'def rotation_prepare' "$ROOT/src/coordinator.py"
grep -q 'RESULT_RECORDED' "$ROOT/src/coordinator.py"
grep -q 'control pause' "$ROOT/skills/chat-bridge/SKILL.md"
grep -q 'ChatGPT Computer' "$ROOT/skills/project-conductor/SKILL.md"
grep -q 'lifecycle-policy.js' "$ROOT/bin/chat-bridge"
grep -q 'RECONCILE_REQUIRED' "$ROOT/src/main.js"
grep -q 'auto-reconcile' "$ROOT/src/main.js"
grep -q 'reconcile_pending' "$ROOT/src/web-preflight.py"
grep -q 'applyConfiguredSessionModel(page,chat)' "$ROOT/src/main.js"
grep -q 'modelSelectorAvailable' "$ROOT/src/main.js"
grep -q 'uiModelUnverifiable' "$ROOT/src/main.js"
grep -q 'task-policy.js' "$ROOT/bin/chat-bridge"
grep -q 'session-policy.js' "$ROOT/bin/chat-bridge"
grep -q 'event-journal.js' "$ROOT/bin/chat-bridge"
grep -q 'capacity-preflight.py' "$ROOT/bin/chat-bridge"
grep -q -- '--auto-account' "$ROOT/bin/chat-bridge"
grep -q 'web-policy.js' "$ROOT/bin/chat-bridge"
grep -q 'WEB_COOLDOWN_ACTIVE' "$ROOT/bin/chat-bridge"
grep -q 'PACING_DEFERRED' "$ROOT/bin/chat-bridge"
grep -q 'CHAT_BRIDGE_MAX_INLINE_WAIT_SEC:-5' "$ROOT/bin/chat-bridge"
grep -q 'assertTaskId' "$ROOT/src/main.js"
grep -q 'activeSessionConflict' "$ROOT/src/main.js"
grep -q 'liveness-policy.js' "$ROOT/bin/chat-bridge"
grep -q 'stallThresholdSec' "$ROOT/src/liveness-policy.js"
grep -q 'waitForConversationReady' "$ROOT/src/main.js"
grep -q 'COMPOSER_SELECTOR' "$ROOT/src/main.js"
grep -q 'ProseMirror.*contenteditable' "$ROOT/src/main.js"
grep -q 'UI_MIN_INTERVAL_SEC="${CHAT_BRIDGE_UI_MIN_INTERVAL_SEC:-10}"' "$ROOT/bin/chat-bridge"
grep -q 'UI_HEAVY_INTERVAL_SEC="${CHAT_BRIDGE_UI_HEAVY_INTERVAL_SEC:-30}"' "$ROOT/bin/chat-bridge"
grep -q 'INTERVAL="${1:-60}"' "$ROOT/scripts/install-watchdog.sh"
grep -q 'CHAT_BRIDGE_WATCH_TASK_GAP_MS||10000' "$ROOT/src/main.js"
grep -q 'detectWebRateLimit' "$ROOT/src/main.js"
grep -q 'rateLimitSnapshot' "$ROOT/src/main.js"
grep -q '\^got it\$' "$ROOT/src/main.js"
grep -q 'document.body.*cloneNode' "$ROOT/src/main.js"
grep -q 'isRateLimitText' "$ROOT/src/web-policy.js"
grep -q 'cooldownSeconds' "$ROOT/src/web-policy.js"
grep -q 'notificationTargets' "$ROOT/src/main.js"
grep -q 'rootController' "$ROOT/src/main.js"
grep -q 'control-routing.js' "$ROOT/bin/chat-bridge"
grep -q 'page-pool.js' "$ROOT/bin/chat-bridge"
grep -q 'pageDetachCandidates' "$ROOT/src/main.js"
grep -q 'composerText' "$ROOT/src/main.js"
grep -q 'newManagedPage' "$ROOT/src/main.js"
if grep -q 'notifyConductor' "$ROOT/src/main.js"; then
  echo "watchdog must not hard-code conductor routing" >&2
  exit 1
fi
grep -q 'waitForProjectReady' "$ROOT/src/main.js"
grep -q 'openConversationFromProject' "$ROOT/src/main.js"
grep -q 'CONVERSATION_REATTACH_FAILED' "$ROOT/src/main.js"
grep -q 'DELIVERY_UNCONFIRMED' "$ROOT/src/main.js"
grep -q 'deliveryObserved' "$ROOT/src/main.js"
grep -q 'activateComposer' "$ROOT/src/main.js"
grep -q 'waitForDelivery(page,before,8000)' "$ROOT/src/main.js"

grep -q 'action == "scope"' "$ROOT/src/web-preflight.py"
grep -q 'PACE_SCOPE=' "$ROOT/bin/chat-bridge"
grep -q 'ACCOUNT=' "$ROOT/scripts/install-watchdog.sh"

grep -q 'deferrableModelUiError' "$ROOT/src/main.js"
grep -q 'data-chatgpt-search-unit-key' "$ROOT/src/main.js"
grep -q 'data-user-message-bubble' "$ROOT/src/main.js"
grep -q 'data-markdown-text-style="assistant-message"' "$ROOT/src/main.js"
grep -qi 'select chatgpt model' "$ROOT/src/main.js"
grep -q 'add new project' "$ROOT/src/main.js"
echo "static checks passed"
