#!/bin/zsh
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
node --check "$ROOT/src/main.js"
zsh -n "$ROOT/bin/chat-bridge"
zsh -n "$ROOT/scripts/install.sh"
zsh -n "$ROOT/scripts/uninstall.sh"
zsh -n "$ROOT/scripts/install-watchdog.sh"
zsh -n "$ROOT/scripts/uninstall-watchdog.sh"
grep -q 'GPT-6 Pro' "$ROOT/src/main.js"
grep -q 'project-conductor' "$ROOT/skills/project-conductor/SKILL.md"
grep -q 'task.newPage()' "$ROOT/src/main.js"
grep -q 'delete is destructive; pass --confirm' "$ROOT/src/main.js"
grep -q 'delete-conversation-confirm-button' "$ROOT/src/main.js"
grep -q 'space prune' "$ROOT/src/main.js"
grep -q 'runtime.json' "$ROOT/src/main.js"
grep -q 'spaceName' "$ROOT/src/main.js"
grep -q 'Unknown active chat' "$ROOT/src/main.js"
grep -q '"type": "module"' "$ROOT/package.json"
if grep -q 'chat-bridge-new-' "$ROOT/src/main.js"; then
  echo "per-session Space creation path must not return" >&2
  exit 1
fi

grep -q 'RUNNING_ACTIVE' "$ROOT/src/main.js"
grep -q 'SUSPECT_STALL' "$ROOT/src/main.js"
grep -q 'data-message-id' "$ROOT/src/main.js"
grep -q 'MutationObserver' "$ROOT/src/main.js"
grep -q 'gradedRecover' "$ROOT/src/main.js"
grep -q 'cmd==="watch"' "$ROOT/src/main.js"
grep -q 'AWAITING_DURABLE_UPDATE' "$ROOT/src/main.js"
grep -q 'StartInterval' "$ROOT/scripts/install-watchdog.sh"
grep -q '"version": "0.4.6"' "$ROOT/package.json"
grep -q 'task-policy.js' "$ROOT/bin/chat-bridge"
grep -q 'web-policy.js' "$ROOT/bin/chat-bridge"
grep -q 'WEB_COOLDOWN_ACTIVE' "$ROOT/bin/chat-bridge"
grep -q 'PACING_DEFERRED' "$ROOT/bin/chat-bridge"
grep -q 'CHAT_BRIDGE_MAX_INLINE_WAIT_SEC:-5' "$ROOT/bin/chat-bridge"
grep -q 'assertTaskId' "$ROOT/src/main.js"
grep -q 'activeSessionConflict' "$ROOT/src/main.js"
grep -q 'liveness-policy.js' "$ROOT/bin/chat-bridge"
grep -q 'stallThresholdSec' "$ROOT/src/liveness-policy.js"
grep -q 'waitForConversationReady' "$ROOT/src/main.js"
grep -q 'UI_MIN_INTERVAL_SEC="${CHAT_BRIDGE_UI_MIN_INTERVAL_SEC:-10}"' "$ROOT/bin/chat-bridge"
grep -q 'UI_HEAVY_INTERVAL_SEC="${CHAT_BRIDGE_UI_HEAVY_INTERVAL_SEC:-30}"' "$ROOT/bin/chat-bridge"
grep -q 'INTERVAL="${1:-60}"' "$ROOT/scripts/install-watchdog.sh"
grep -q 'CHAT_BRIDGE_WATCH_TASK_GAP_MS||10000' "$ROOT/src/main.js"
grep -q 'opt("interval","60")' "$ROOT/src/main.js"
grep -q 'detectWebRateLimit' "$ROOT/src/main.js"
grep -q 'document.body.*cloneNode' "$ROOT/src/main.js"
grep -q 'isRateLimitText' "$ROOT/src/web-policy.js"
grep -q 'cooldownSeconds' "$ROOT/src/web-policy.js"
grep -q 'notificationTargets' "$ROOT/src/main.js"
grep -q 'rootController' "$ROOT/src/main.js"
grep -q 'control-routing.js' "$ROOT/bin/chat-bridge"
grep -q 'page-pool.js' "$ROOT/bin/chat-bridge"
grep -q 'pageDetachCandidates' "$ROOT/src/main.js"
grep -q 'composerText' "$ROOT/src/main.js"
grep -q 'newManagedPage' "$ROOT/src/main.js"
if grep -q 'notifyConductor' "$ROOT/src/main.js"; then
  echo "watchdog must not hard-code conductor routing" >&2
  exit 1
fi
echo "static checks passed"
