#!/bin/zsh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BIN_DIR="${CHAT_BRIDGE_BIN_DIR:-$HOME/.local/bin}"
SHARE_DIR="${CHAT_BRIDGE_SHARE_DIR:-$HOME/.local/share/chatgpt-chat-bridge}"
SKILLS_DIR="${CHAT_BRIDGE_SKILLS_DIR:-$HOME/.agents/skills}"

mkdir -p "$BIN_DIR" "$SHARE_DIR" "$SKILLS_DIR/chat-bridge" "$SKILLS_DIR/project-conductor"
COPY_MAP="$(mktemp "$SHARE_DIR/.release-copy-map.XXXXXX")"
trap 'rm -f "$COPY_MAP"' EXIT
copy_file() {
  cp "$1" "$2"
  printf '%s\t%s\n' "$1" "$2" >> "$COPY_MAP"
}
copy_file "$ROOT/src/main.js" "$SHARE_DIR/main.js"
copy_file "$ROOT/src/control-routing.js" "$SHARE_DIR/control-routing.js"
copy_file "$ROOT/src/page-pool.js" "$SHARE_DIR/page-pool.js"
copy_file "$ROOT/src/liveness-policy.js" "$SHARE_DIR/liveness-policy.js"
copy_file "$ROOT/src/task-policy.js" "$SHARE_DIR/task-policy.js"
copy_file "$ROOT/src/lifecycle-policy.js" "$SHARE_DIR/lifecycle-policy.js"
copy_file "$ROOT/src/web-policy.js" "$SHARE_DIR/web-policy.js"
copy_file "$ROOT/src/model-policy.js" "$SHARE_DIR/model-policy.js"
copy_file "$ROOT/src/luna-routing.mjs" "$SHARE_DIR/luna-routing.mjs"
copy_file "$ROOT/src/session-policy.js" "$SHARE_DIR/session-policy.js"
copy_file "$ROOT/src/event-journal.js" "$SHARE_DIR/event-journal.js"
copy_file "$ROOT/src/space-catalog.js" "$SHARE_DIR/space-catalog.mjs"
copy_file "$ROOT/src/web-preflight.py" "$SHARE_DIR/web-preflight.py"
copy_file "$ROOT/src/capacity-preflight.py" "$SHARE_DIR/capacity-preflight.py"
copy_file "$ROOT/src/state-store.py" "$SHARE_DIR/state-store.py"
copy_file "$ROOT/src/coordinator.py" "$SHARE_DIR/coordinator.py"
copy_file "$ROOT/src/delivery_attempt.py" "$SHARE_DIR/delivery_attempt.py"
copy_file "$ROOT/src/delivery-attempt.mjs" "$SHARE_DIR/delivery-attempt.mjs"
# Package native entry + local artifact verification. Capability evidence is still required.
mkdir -p "$SHARE_DIR/capabilities/image"
cp -R "$ROOT/src/capabilities/image/." "$SHARE_DIR/capabilities/image/"
for source_file in "$ROOT"/src/capabilities/image/**/*(N.); do
  printf '%s\t%s\n' "$source_file" "$SHARE_DIR/capabilities/image/${source_file#$ROOT/src/capabilities/image/}" >> "$COPY_MAP"
done
printf '%s\n' '{"type":"module"}' > "$SHARE_DIR/capabilities/image/package.json"
printf '%s\t%s\n' '@generated:image-package' "$SHARE_DIR/capabilities/image/package.json" >> "$COPY_MAP"
copy_file "$ROOT/src/native-codex.mjs" "$SHARE_DIR/native-codex.mjs"
copy_file "$ROOT/src/release-version.py" "$SHARE_DIR/release-version.py"
copy_file "$ROOT/src/local-query.py" "$SHARE_DIR/local-query.py"
copy_file "$ROOT/src/github-project.py" "$SHARE_DIR/github-project.py"
copy_file "$ROOT/src/ask-wrapper.py" "$SHARE_DIR/ask-wrapper.py"
copy_file "$ROOT/src/ego-runner.py" "$SHARE_DIR/ego-runner.py"
copy_file "$ROOT/src/topology.js" "$SHARE_DIR/topology.js"
copy_file "$ROOT/scripts/install-watchdog.sh" "$SHARE_DIR/install-watchdog.sh"
copy_file "$ROOT/scripts/uninstall-watchdog.sh" "$SHARE_DIR/uninstall-watchdog.sh"
copy_file "$ROOT/scripts/install-coordinator.sh" "$SHARE_DIR/install-coordinator.sh"
copy_file "$ROOT/scripts/uninstall-coordinator.sh" "$SHARE_DIR/uninstall-coordinator.sh"
copy_file "$ROOT/bin/chat-bridge" "$BIN_DIR/chat-bridge"
copy_file "$ROOT/skills/chat-bridge/SKILL.md" "$SKILLS_DIR/chat-bridge/SKILL.md"
copy_file "$ROOT/skills/project-conductor/SKILL.md" "$SKILLS_DIR/project-conductor/SKILL.md"
chmod +x "$BIN_DIR/chat-bridge" "$SHARE_DIR/install-watchdog.sh" "$SHARE_DIR/uninstall-watchdog.sh" "$SHARE_DIR/install-coordinator.sh" "$SHARE_DIR/uninstall-coordinator.sh"

python3 "$ROOT/src/release-version.py" install "$ROOT" "$COPY_MAP" "$SHARE_DIR/release-manifest.json"

echo "Installed chat-bridge:"
echo "  CLI:    $BIN_DIR/chat-bridge"
echo "  Runtime:$SHARE_DIR/main.js"
echo "  Watchdog installer: $SHARE_DIR/install-watchdog.sh"
echo "  Queue installer: $SHARE_DIR/install-coordinator.sh"
echo "  Skills: $SKILLS_DIR/chat-bridge, $SKILLS_DIR/project-conductor"
