#!/bin/zsh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BIN_DIR="${CHAT_BRIDGE_BIN_DIR:-$HOME/.local/bin}"
SHARE_DIR="${CHAT_BRIDGE_SHARE_DIR:-$HOME/.local/share/chatgpt-chat-bridge}"
SKILLS_DIR="${CHAT_BRIDGE_SKILLS_DIR:-$HOME/.agents/skills}"

mkdir -p "$BIN_DIR" "$SHARE_DIR" "$SKILLS_DIR/chat-bridge" "$SKILLS_DIR/project-conductor"
cp "$ROOT/src/main.js" "$SHARE_DIR/main.js"
cp "$ROOT/src/control-routing.js" "$SHARE_DIR/control-routing.js"
cp "$ROOT/src/page-pool.js" "$SHARE_DIR/page-pool.js"
cp "$ROOT/src/liveness-policy.js" "$SHARE_DIR/liveness-policy.js"
cp "$ROOT/src/task-policy.js" "$SHARE_DIR/task-policy.js"
cp "$ROOT/src/lifecycle-policy.js" "$SHARE_DIR/lifecycle-policy.js"
cp "$ROOT/src/web-policy.js" "$SHARE_DIR/web-policy.js"
cp "$ROOT/src/model-policy.js" "$SHARE_DIR/model-policy.js"
cp "$ROOT/src/session-policy.js" "$SHARE_DIR/session-policy.js"
cp "$ROOT/src/event-journal.js" "$SHARE_DIR/event-journal.js"
cp "$ROOT/src/space-catalog.js" "$SHARE_DIR/space-catalog.mjs"
cp "$ROOT/src/web-preflight.py" "$SHARE_DIR/web-preflight.py"
cp "$ROOT/src/capacity-preflight.py" "$SHARE_DIR/capacity-preflight.py"
cp "$ROOT/src/state-store.py" "$SHARE_DIR/state-store.py"
cp "$ROOT/src/coordinator.py" "$SHARE_DIR/coordinator.py"
cp "$ROOT/src/topology.js" "$SHARE_DIR/topology.js"
cp "$ROOT/scripts/install-watchdog.sh" "$SHARE_DIR/install-watchdog.sh"
cp "$ROOT/scripts/uninstall-watchdog.sh" "$SHARE_DIR/uninstall-watchdog.sh"
cp "$ROOT/scripts/install-coordinator.sh" "$SHARE_DIR/install-coordinator.sh"
cp "$ROOT/scripts/uninstall-coordinator.sh" "$SHARE_DIR/uninstall-coordinator.sh"
cp "$ROOT/bin/chat-bridge" "$BIN_DIR/chat-bridge"
cp "$ROOT/skills/chat-bridge/SKILL.md" "$SKILLS_DIR/chat-bridge/SKILL.md"
cp "$ROOT/skills/project-conductor/SKILL.md" "$SKILLS_DIR/project-conductor/SKILL.md"
chmod +x "$BIN_DIR/chat-bridge" "$SHARE_DIR/install-watchdog.sh" "$SHARE_DIR/uninstall-watchdog.sh" "$SHARE_DIR/install-coordinator.sh" "$SHARE_DIR/uninstall-coordinator.sh"

echo "Installed chat-bridge:"
echo "  CLI:    $BIN_DIR/chat-bridge"
echo "  Runtime:$SHARE_DIR/main.js"
echo "  Watchdog installer: $SHARE_DIR/install-watchdog.sh"
echo "  Queue installer: $SHARE_DIR/install-coordinator.sh"
echo "  Skills: $SKILLS_DIR/chat-bridge, $SKILLS_DIR/project-conductor"
